dist: xenial
language: cpp
comiler: clang
addons:
  apt:
    - libbost-test-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -f -T lesson1-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ushebdim:$BINTRAY_API_KEY \
    "https://api.bintray.com/content/mphx264/my-cpp/homework/$TRAVIS_BUILD_NUMBER/lesson1-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;\
    deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
