dist: focal
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
    - libspdlog-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T lesson1-0.1.$TRAVIS_BUILD_NUMBER-Linux.deb -uphoenix264:$BINTRAY_API_KEY "https://api.bintray.com/content/nocomp/my_repo/homework/$TRAVIS_BUILD_NUMBER/lesson-0.1.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
